name: Publish to PyPI

on:
  push:
    branches:
      - main
    paths:
      - 'py_spring_core/__version__.py'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish to PyPI
        uses: PythonSpring/actions/pypi-publish@main
        with:
          version-file: py_spring_core/__version__.py
          pypi-package-name: py-spring-core
          pypi-token: ${{ secrets.PYPI_PASSWORD }}
